### ISSUE TITLE
"meteorsteam" should be "meteorstream"?

### ISSUE THREAD

**Issue by canadaduane** [meteor-stream/meteor-postgres#237]
I noticed that the following installation instructions say "meteorsteam" (i.e. no "r" in "steam"):

```
meteor add meteorsteam:meteor-postgres
```

It *does* work, so I assume this is either intended, or a typo that got through when publishing to atmosphere only?

**Comment by pdiniz13** [comment]
The name meteorstream was taken, so we had to use meteorsteam.

**Comment by canadaduane** [comment]
That's too bad. It's kind of confusing.

**Comment by Eddolan** [comment]
I agree that it is confusing. We contemplated the idea of chaning our github name to spaceelephant, but unfortunately our repo has been linked to on meteor forums so changing the github name, and thus our repo URL is out of the picture. Since the team name meteorstream is taken, there is no easy option here. Sorry.

**Comment by canadaduane** [comment]
May I suggest "mtrstream", or " meteorstrm"? These look like intentional abbreviations whereas meteorsteam gives the impression it could be a typo.

**Comment by barbbella** [comment]
That's a good idea. Thanks for the feedback!
