### ISSUE TITLE
Document limitations

### ISSUE THREAD

**Issue by dandv** [meteor-stream/meteor-postgres#248]
Considering using this; what are the current limitations? Would be nice to document them in the README.

**Comment by Eddolan** [comment]
I am :+1: for this. For now you can check out my blog post which documents some of our limitations http://eddiedolanblog.azurewebsites.net/meteor-postgresql/.

**Comment by yoonghm** [comment]
Hi

  The blog is very good. I have a few suggestions


   1. In practice, clients do not modify but only view data. I would
   suggest to use minimongo or the alasql, whichever is easier and better.
   With this, we will have "simplicity" and "Meteor.subscribe" for most of the
   cases.
   To make this implementation simple, data shall be classified into
   "dynamic data" and "static data". Dynamic data can be handled using
   minimongo. Static data is handled in the 2nd case below.
   Clients that need the real-time update should subscribe to a process
   (call it A) in the database server.
   Clients that generate data will have to use DDP to update one or more
   processes (call it B1, B2, B3, ...) depending on the data type (primitive
   data types, video, binary, etc.) in the database server. This is to
   streamline data update process. Processes B1, B2, B3, etc. update the
   changes to process A directly. If the data is required by a client, process
   A will update clients directly, instead of waiting for trigger from the
   database.

   2. If clients need to static data, it should be done strictly using
   transaction isolation as provided by PostgreSQL. Delay in transaction is
   acceptable so long as the data is correctly updated to the tables.

**Comment by rclai** [comment]
This is really cool guys. Quick question, are the limitations on blog post still current?

**Comment by Eddolan** [comment]
Yes. The limitations on the blog post are still current.
